import 'package:aiphotogallery/screens/home_screen/upload_photos.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:responsive_sizer/responsive_sizer.dart';

class GetStartedScreen extends StatefulWidget {
  const GetStartedScreen({Key? key}) : super(key: key);

  @override
  State<GetStartedScreen> createState() => _GetStartedScreenState();
}

class _GetStartedScreenState extends State<GetStartedScreen> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        backgroundColor: Colors.white,
        body: Container(
          color: Colors.white,
          width: Adaptive.w(100),
          height: Adaptive.h(100),
          padding: EdgeInsets.only(top: 15.sp),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: EdgeInsets.only(left: 15.sp, right: 15.sp),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        CircleAvatar(
                          radius: 16.sp,
                          backgroundColor: Colors.orange.withOpacity(0.1),
                          child: Text(
                            '1',
                            style: textStyle,
                          ),
                        ),
                        SizedBox(width: 15.sp),
                        Container(
                          width: Adaptive.w(80),
                          child: Text(
                            'Upload photos of yourself',
                            style: textStyle,
                          ),
                        ),
                      ],
                    ),
                    SizedBox(
                      height: 12.sp,
                    ),
                    SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        children: List.generate(3, (index) {
                          return Container(
                            height: 43.sp,
                            width: 44.sp,
                            child: Padding(
                              padding: EdgeInsets.only(left: 7.sp, right: 7.sp),
                              child: ClipRRect(
                                  borderRadius: BorderRadius.circular(15.sp),
                                  child: Image.network(
                                      'https://www.bhaktiphotos.com/wp-content/uploads/2018/04/Mahadev-Bhagwan-Photo-for-Devotee.jpg',
                                      fit: BoxFit.cover)),
                            ),
                          );
                        }),
                      ),
                    )
                  ],
                ),
              ),
              SizedBox(
                height: 18.sp,
              ),
              column(
                  '2',
                  'Receive 200+ beautiful avatars generated by advanced AI',
                  'https://t4.ftcdn.net/jpg/02/59/73/73/360_F_259737328_RIlTbe7EgSgz00SviZJOMWR7yZtcrva8.jpg'),
              SizedBox(
                height: 18.sp,
              ),
              column(
                  '3',
                  'Expand your favourites to get even bigger and higher-quality avatars',
                  'https://media.istockphoto.com/id/1294339577/photo/young-beautiful-woman.jpg?s=612x612&w=0&k=20&c=v41m_jNzYXQtxrr8lZ9dE8hH3CGWh6HqpieWkdaMAAM='),
              Spacer(),
              SizedBox(
                width: Adaptive.w(100),
                height: 28.sp,
                child: Padding(
                  padding: EdgeInsets.only(left: 17.sp, right: 17.sp),
                  child: ElevatedButton(
                      onPressed: () {
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => UploadPhotos()));
                      },
                      style: ElevatedButton.styleFrom(
                          shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(25.sp),
                      )),
                      child: Text(
                        'Get Started',
                        style: TextStyle(color: Colors.white, fontSize: 16.sp),
                      )),
                ),
              ),
              SizedBox(
                height: 15.sp,
              ),
              Align(
                alignment: Alignment.center,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Text('By getting started, you agree to', style: textStyle2),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text('our ', style: textStyle2),
                        Text('Terms and Privacy Policy',
                            style: textStyle2.copyWith(
                              decoration: TextDecoration.underline,
                            )),
                      ],
                    ),
                  ],
                ),
              ),
              SizedBox(
                height: 25.sp,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget column(String number, String text, String url) {
    return Padding(
      padding: EdgeInsets.only(left: 15.sp, right: 0.sp),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              CircleAvatar(
                radius: 16.sp,
                backgroundColor: Colors.orange.withOpacity(0.1),
                child: Text(
                  number,
                  style: textStyle,
                ),
              ),
              SizedBox(width: 12.sp),
              Container(
                width: Adaptive.w(80),
                child: Text(
                  text,
                  style: textStyle,
                ),
              ),
            ],
          ),
          SizedBox(
            height: 15.sp,
          ),
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: List.generate(5, (index) {
                return Container(
                  height: 43.sp,
                  width: 44.sp,
                  child: Padding(
                    padding: EdgeInsets.only(left: 7.sp, right: 7.sp),
                    child: ClipRRect(
                        borderRadius: BorderRadius.circular(15.sp),
                        child: Image.network(url, fit: BoxFit.cover)),
                  ),
                );
              }),
            ),
          )
        ],
      ),
    );
  }

  TextStyle textStyle2 = TextStyle(
      fontSize: 16.sp, fontWeight: FontWeight.normal, color: Colors.grey);
  TextStyle textStyle = TextStyle(
      fontSize: 16.sp, fontWeight: FontWeight.bold, color: Colors.black);
}
